### ISSUE TITLE
Use POST for _mtermvectors request

### ISSUE THREAD

**Issue by pratheekrebala** [federicotdn/inelastic#4]
By default, using the `ids` parameter as used here: https://github.com/federicotdn/inelastic/blob/master/inelastic.py#L82 sends all the ids for a batch as a parameter in a single GET request.

I think this is causing an issue when passing in a huge number of document ids (when `search_size` is large).

Using the `body` parameter instead of `ids` will allow you to pass as many ids as possible.

This will also address: https://github.com/federicotdn/inelastic/issues/1

Also discussed here: https://github.com/elastic/elasticsearch-py/issues/825#issuecomment-422541389

**Comment by federicotdn** [comment]
Good observation! You're right, it would make more sense to pass them via the `body` parameter. Are you interested in submitting a PR with this change?

**Comment by pratheekrebala** [comment]
Yup - PR is available here: https://github.com/federicotdn/inelastic/pull/5

I have another branch (https://github.com/pratheekrebala/inelastic/tree/v6) which does the same fix for the ES v6 version of the tool. Any idea how to make a PR that would update that specific release?

**Comment by federicotdn** [comment]
Just merged it, thanks a lot. About the v6 version - I haven't decided yet how I'm going to handle both versions in parallel (the v7 version is quite recent). The devs in charge of [elasticsearch-py](https://github.com/elastic/elasticsearch-py) seem to have separate branches for older versions, backporting fixes (I assume) as they go. This seems to be a good option, but it requires a bit more development time.

I'm thinking of using the `pip` argument `--install-option` (https://pip.pypa.io/en/stable/reference/pip_install/#options) to maybe select the Elasticsearch version when installing `inelastic`. The elasticsearch-py version would then be selected according to what the user specified. Some parts of the module would then need to adapt themselves depending on the installed version (dynamically). All of this may be a bit hacky though.

**Comment by federicotdn** [comment]
Just realized the elasticsearch-py devs release older versions as separate packages (`elasticsearch6`, `elasticsearch5`, etc.), which should make things much easier. I think I'll maintain only one version of `inelastic` which will be simultaneously compatible with ES 6 and 7. Therefore, backporting your fix won't be necessary.

**Comment by federicotdn** [comment]
The fix is now included in the `0.2.4` version of the module, for both ES 6 and 7.
